SELECT
    e.EMPLOYEE_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
    e.SALARY,
    e.DEPARTMENT_ID,
    d.DEPARTMENT_NAME,
    l.LOCATION_ID,
    l.CITY,
    l.STATE_PROVINCE,
    c.COUNTRY_NAME,
    r.REGION_NAME

FROM
    HR.EMPLOYEES e

LEFT JOIN
    HR.DEPARTMENTS d 
        ON e.DEPARTMENT_ID = d.department_id

LEFT JOIN
    HR.LOCATIONS L
        ON d.LOCATION_ID = l.LOCATION_ID

LEFT JOIN
    HR.COUNTRIES C
        ON l.COUNTRY_ID = c.COUNTRY_ID

LEFT JOIN HR.REGIONS r
    ON c.REGION_ID = r.REGION_ID

WHERE e.DEPARTMENT_ID IS NOT NULL

ORDER BY
    r.REGION_NAME,
    c.COUNTRY_NAME,
    l.CITY,
    e.SALARY DESC